"""
This file contains all the test data that is to be entered into the Integration Test Home Page
"""


class TestData:
    GECKODRIVER_PATH = "C:/Users/Harshock/PycharmProjects/RPM-Exercise-2020/geckodriver.exe"
    BASE_URL = "https://rpmsoftware.com/hiring/2020/integration-test/form-edit.html"
    FINAL_URL = "https://rpmsoftware.com/hiring/2020/integration-test/form.html#"
    EMPLOYEE_NAME = "Isabel Britt"
    SUMMARY = "This is a test Employee Summary."
    DEPARTMENT = "Management"
    SALARY = "$50,000.00"
    ADDRESS_LAT = "34.833850°"
    ADDRESS_LONG = "106.748580°"
    WORK_LOCATION = "Headquarters"
    DATE_OF_JOINING = "2018-01-04"
    CUBICLE_LENGTH = "47"
    CUBICLE_WIDTH = "21"
    METRIC = "In"
    CUBICLE_COLOR = "Brown"
    ROW1_COLUMN1 = "Ford"
    ROW1_COLUMN2 = "Taurus"
    ROW1_COLUMN3 = "2018"
    ROW1_COLUMN4 = "SEL"
    ROW1_COLUMN5 = "Black"
    ROW1_COLUMN6 = "TEST-0001"
    ROW2_COLUMN1 = "Ford"
    ROW2_COLUMN2 = "F150"
    ROW2_COLUMN3 = "2015"
    ROW2_COLUMN4 = "XLT"
    ROW2_COLUMN5 = "Red"
    ROW2_COLUMN6 = "Test-0002"
