"""
This file contains all the test data that is to be entered into the Integration Test Home Page
"""


class TestData:
    GECKODRIVER_PATH = "C:/Users/Harshock/PycharmProjects/RPM-Exercise-2020/geckodriver.exe"
    BASE_URL = "https://rpmsoftware.com/hiring/2020/integration-test/form-edit.html"
    FINAL_URL = "https://rpmsoftware.com/hiring/2020/integration-test/form.html#"
    EMPLOYEE_NAME = "Isabel Britt"
    SUMMARY = "This is a test Employee Summary."
    DEPARTMENT = "Management"
    SALARY = "$50,000.00"
    ADDRESS_LAT = "34.833850°"
    ADDRESS_LONG = "106.748580°"
    WORK_LOCATION = "Headquarters"
    DATE_OF_JOINING = "2018-01-04"
    CUBICLE_LENGTH = "47"
    CUBICLE_WIDTH = "21"
    METRIC = "in"
    CUBICLE_COLOR = "Brown"
    CAR1_BRAND = "Ford"
    CAR1_MODEL = "Taurus"
    CAR1_MODEL_YEAR = "2018"
    CAR1_TRIM = "SEL"
    CAR1_COLOR = "Black"
    CAR1_LICENCE_PLATE = "TEST-0001"
    CAR2_BRAND = "Ford"
    CAR2_MODEL = "F150"
    CAR2_MODEL_YEAR = "2015"
    CAR2_TRIM = "XLT"
    CAR2_COLOR = "Red"
    CAR2_LICENCE_PLATE = "Test-0002"
